workflows:
  build-capacitor:
    name: Build Capacitor Android (with Firebase files)
    environment:
      vars:
        NODE_VERSION: "18"
        BUILD_TYPE: "debug"
    scripts:
      - name: Setup Node
        script: |
          if command -v node >/dev/null 2>&1; then
            echo "Node found: $(node -v)"
          else
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
          fi

      - name: Install deps & build web
        script: |
          npm ci
          npm run build

      - name: Capacitor sync
        script: |
          npm i @capacitor/cli @capacitor/core --no-save
          npx cap add android || true
          npx cap sync android

      - name: Write Firebase files
        script: |
          mkdir -p android/app
          echo "$ANDROID_GOOGLE_SERVICES_BASE64" | base64 --decode > android/app/google-services.json

      - name: Prepare Android keystore (optional)
        script: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.jks

            cat <<EOF > android/gradle.properties
KEYSTORE_FILE=my-release-key.jks
KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD
KEY_ALIAS=$ANDROID_KEY_ALIAS
KEY_PASSWORD=$ANDROID_KEY_PASSWORD
EOF
          else
            echo "No keystore provided. Debug build will still work."
          fi

      - name: Android build
        script: |
          cd android
          if [ "$BUILD_TYPE" = "release" ]; then
            ./gradlew assembleRelease -x lint
          else
            ./gradlew assembleDebug -x lint
          fi

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
